language: node_js
node_js:
- '6.9'
after_success:
- npm run coverage
before_deploy: npm run predeploy
deploy:
  provider: npm
  email: opensource@eze.tech
  api_key:
    secure: l6Hj7KnzUnG1DzfPcNsDsVAKxm2bCtuLfPtt7USrx5B4VO5zL6XNCWSlqZP6sK+r5rUhUTqLQnQSqL/102Zz0qwGve6F4YWPrDP+FOZQyHS5ubIjbPFrTckaMWcsXDN1tEHfthijm4nGjU61tRs9hcYTbPFG2fdFjE2N9o1Mp5Q5RC8KPW0ziDuS/BK823Rsuu6RPqIF9SYJFFejQxZtWkiffXT/wvpVOwuSAVNpo4yz6Nraq04QmHjrpvnihXYNAPDbhqS2q7byL+KbP1jBCDAaBF4DaFS/6c97k+dVMgRjmnv0Re1SoZ5PjWKmzLWNwa9km+4NlYZie3mxgPWyjNfnf1Ce7I+kGGKylxgl+jPmokSYoRLizDkOkPcE1C5Yc1MCbr0YWDTlQdYcBBff08oTxOhYhMRlLJXNZiME47B4M8KpG+vFD78rDaxrr/M57r8V8wi443ruoiupzsc1yt/vV+zPFb2pbWTtO9iKcRiVyJWkQKqfeuxTYKzEhmipsdYKKVMsi17mojppSxmAPvEcLygram4F0VFpWnV6iy2o/YwEWJigzMsJht66PcOPEpxrEO/GnsqmNuZ7MrThOj8qn9qnLLq+bKELLe/kUeDGAiHGxkaE3qRSBdBEiYA3UatdoC72A/SgLot4S9qoawjjiMGIOlDFuQ+mRGlKXc0=
  on:
    tags: true
    repo: ezetech/react-multi-level-menu-component
